language: java
dist: trusty
jdk:
    - oraclejdk8

sudo: false

install:
    - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn test -P !build-extras -B

cache:
    directories:
        - ~/.m2/repository

after_success:
    - /bin/sh ./before_deploy.sh
    - /bin/sh ./deploy.sh
